apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-backend-image
  newName: 471112665279.dkr.ecr.ap-northeast-2.amazonaws.com/humancat-backend:0.0.1-backend.01
  newTag: 0.0.1-backend.01
namespace: gitops
